### ISSUE TITLE
Could not read config file from en_acl_terms_sm-2.0.4\config.cfg

### ISSUE THREAD

**Issue by Antoni0111** [kevinlu1248/pyate#60]
Hello, Kevin.
When I download en_acl_terms_sm-2.0.4..tar.gz by IDM downloader and use pip install this packages in cmd successfully. 
However when i input 
>>> import spacy
>>>
>>> nlp = spacy.load("en_acl_terms_sm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\__init__.py", line 51, in load
    return util.load_model(
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 420, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 453, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\en_acl_terms_sm\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 615, in load_model_from_init_py
    return load_model_from_path(
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 487, in load_model_from_path
    config = load_config(config_path, overrides=overrides)
  File "C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\spacy\util.py", line 646, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from C:\Users\WcisapoorguY\AppData\Local\Programs\Python\Python310\lib\site-packages\en_acl_terms_sm\en_acl_terms_sm-2.0.4\config.cfg

then i check the path, but there is no  "config.cfg" file in  root directory
And i try to reinstall the en_acl_terms_sm-2.0.4..tar.gz, still get the same result.

Here is my pip packages list:
C:\WINDOWS\system32>pip list
Package            Version
------------------ ---------
blis               0.7.7
catalogue          2.0.7
certifi            2021.10.8
charset-normalizer 2.0.12
click              8.0.4
colorama           0.4.4
cymem              2.0.6
en-acl-terms-sm    2.0.4
en-core-web-sm     3.2.0
idna               3.3
Jinja2             3.1.1
langcodes          3.3.0
MarkupSafe         2.1.1
murmurhash         1.0.6
numpy              1.22.3
packaging          21.3
pandas             1.4.2
pathy              0.6.1
pip                22.0.4
preshed            3.0.6
pyahocorasick      1.4.4
pyate              0.5.3
pydantic           1.8.2
pyparsing          3.0.7
python-dateutil    2.8.2
pytz               2022.1
requests           2.27.1
setuptools         62.0.0
six                1.16.0
smart-open         5.2.1
spacy              3.2.4
spacy-legacy       3.0.9
spacy-loggers      1.0.2
srsly              2.4.2
thinc              8.0.15
tqdm               4.64.0
typer              0.4.1
typing_extensions  4.1.1
urllib3            1.26.9
wasabi             0.9.1
wheel              0.37.1

(sorry for my poor english, and i am a beginner of using python )

[en_acl_terms_sm-2.0.4.tar.gz](https://github.com/kevinlu1248/pyate/files/8456824/en_acl_terms_sm-2.0.4.tar.gz)

**Comment by kevinlu1248** [comment]
Sorry for the late response. The issue is that en_acl_terms_sm-2.0.4..tar.gz was actually trained with spacy v2.0. I will clarify in the README when I get the chance.
